name: Deploy Site

on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "30 23 * * 3,6"
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      USER: hantang
      REPO: bookworm-doc

    steps:
      - name: Checkout site
        uses: actions/checkout@v4
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.REPO }}
          fetch-depth: 1
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Build Site
        run: bash ${{ env.REPO }}/deploy.sh ${{ env.REPO }}
      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
